-- 在线商品小站 - 数据库初始化脚本
-- MariaDB 兼容语法

CREATE DATABASE IF NOT EXISTS online_shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE online_shop;

-- 管理员表
CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) DEFAULT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin',
  isActive TINYINT NOT NULL DEFAULT 1,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 商品分类表
CREATE TABLE IF NOT EXISTS product_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  code VARCHAR(20) NOT NULL UNIQUE,
  description VARCHAR(200) DEFAULT NULL,
  smsEnabled INT NOT NULL DEFAULT 0 COMMENT '是否需要接码: 1需要 0不需要',
  smsPrice DECIMAL(10,2) DEFAULT NULL COMMENT '接码额外费用',
  smsPaymentName VARCHAR(100) DEFAULT NULL COMMENT '接码支付显示名称',
  smKeyWord VARCHAR(100) DEFAULT NULL COMMENT '接码关键词',
  sort INT NOT NULL DEFAULT 0 COMMENT '排序',
  `show` INT NOT NULL DEFAULT 1 COMMENT '是否显示',
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 商品表
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(100) DEFAULT NULL COMMENT '商品代号（用于支付订单）',
  price DECIMAL(10,2) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  image VARCHAR(500) DEFAULT NULL,
  categoryId INT DEFAULT NULL COMMENT '商品类别ID',
  sales INT NOT NULL DEFAULT 0,
  warranty VARCHAR(200) DEFAULT NULL,
  credit INT DEFAULT NULL COMMENT '积分额度（商品级别）',
  tips VARCHAR(500) DEFAULT NULL,
  addr VARCHAR(500) DEFAULT NULL COMMENT '兑换地址（CDK使用地址）',
  `show` INT NOT NULL DEFAULT 1 COMMENT '是否在首页显示: 1显示 0隐藏',
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY IDX_products_categoryId (categoryId),
  CONSTRAINT FK_products_category FOREIGN KEY (categoryId) REFERENCES product_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) DEFAULT NULL,
  avatar VARCHAR(500) DEFAULT NULL,
  isActive TINYINT NOT NULL DEFAULT 1,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 卡密表
CREATE TABLE IF NOT EXISTS card_keys (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  productId INT DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  keyword VARCHAR(100) DEFAULT NULL,
  CDK VARCHAR(32) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'unused',
  deliveryInfo VARCHAR(1000) DEFAULT NULL COMMENT '发货凭证（邮箱/密码/2FA等）',
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  usedAt DATETIME(6) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 订单表
CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderNo VARCHAR(64) NOT NULL UNIQUE,
  userId INT DEFAULT NULL,
  cardKeyId INT DEFAULT NULL,
  productId INT NOT NULL,
  amount DECIMAL(10,2) DEFAULT NULL COMMENT '订单金额',
  payMethod VARCHAR(20) DEFAULT NULL COMMENT '兑换 / alipay',
  tradeNo VARCHAR(64) DEFAULT NULL COMMENT '支付宝交易号',
  contact VARCHAR(100) NOT NULL COMMENT '联系方式',
  phone VARCHAR(20) DEFAULT NULL COMMENT '接码手机号',
  verifyCode VARCHAR(20) DEFAULT NULL COMMENT '验证码',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  remark VARCHAR(500) DEFAULT NULL,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  completedAt DATETIME(6) DEFAULT NULL,
  couponId INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 短信记录表
CREATE TABLE IF NOT EXISTS sms_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(20) NOT NULL COMMENT '获取的手机号',
  keyword VARCHAR(100) DEFAULT NULL COMMENT '短信关键词',
  cardType VARCHAR(20) DEFAULT '全部' COMMENT '卡类型：实卡/虚卡/全部',
  smsContent TEXT DEFAULT NULL COMMENT '短信原文内容',
  verifyCode VARCHAR(20) DEFAULT NULL COMMENT '提取的验证码',
  status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active/completed/released/blocked',
  ip VARCHAR(45) DEFAULT NULL COMMENT '请求者IP',
  source VARCHAR(20) NOT NULL DEFAULT 'free' COMMENT '来源：free/iscode',
  cardKeyId INT DEFAULT NULL COMMENT '关联卡密ID',
  productId INT DEFAULT NULL COMMENT '关联商品ID',
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 支付订单表
CREATE TABLE IF NOT EXISTS payment_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT DEFAULT NULL,
  orderNo VARCHAR(64) NOT NULL UNIQUE,
  tradeNo VARCHAR(64) DEFAULT NULL,
  productId INT NOT NULL,
  productName VARCHAR(200) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  qrCode VARCHAR(500) DEFAULT NULL,
  contact VARCHAR(100) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  paidAt DATETIME(6) DEFAULT NULL,
  expiredAt DATETIME(6) DEFAULT NULL,
  notifyData TEXT DEFAULT NULL,
  cardKeyId INT DEFAULT NULL,
  cdKey VARCHAR(200) DEFAULT NULL,
  couponId INT DEFAULT NULL,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 速率限制配置表
CREATE TABLE IF NOT EXISTS rate_limit_configs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(50) NOT NULL UNIQUE COMMENT '配置键名',
  name VARCHAR(50) NOT NULL COMMENT '配置名称',
  windowMs INT NOT NULL COMMENT '时间窗口（毫秒）',
  maxRequests INT NOT NULL COMMENT '最大请求数',
  message TEXT DEFAULT NULL COMMENT '限制提示信息',
  enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
  createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 激活码表
CREATE TABLE IF NOT EXISTS activation_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  type VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'unused',
  usedBy INT DEFAULT NULL,
  usedAt DATETIME(6) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expiredAt DATETIME(6) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 优惠码表
CREATE TABLE IF NOT EXISTS coupons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  productId INT DEFAULT NULL COMMENT 'null=全部商品',
  discount DECIMAL(5,2) DEFAULT NULL COMMENT '百分比折扣',
  deduction DECIMAL(10,2) DEFAULT NULL COMMENT '固定抵扣金额',
  maxUses INT DEFAULT NULL COMMENT '最大使用次数',
  usedCount INT NOT NULL DEFAULT 0,
  validFrom DATETIME(6) DEFAULT NULL,
  validTo DATETIME(6) DEFAULT NULL,
  userId INT DEFAULT NULL COMMENT '限定使用者',
  bindIp VARCHAR(45) DEFAULT NULL COMMENT '限定IP',
  requireLogin BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
